FloriShop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls', namespace='main')),
]

cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'
urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),

    path('list/', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse

class Blog(models.Model):
    title = models.CharField('Тема поста', max_length=99)
    post = models.TextField('Текст поста')


    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'Посты'
        verbose_name_plural = 'Блог'


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_list_by_category',
                       args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey('Category', related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_detail',
                       args=[self.id, self.slug])

main/forms.py
from .models import Blog
from django import forms
from django.forms import ModelForm, TextInput, Textarea, EmailField
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', help_text='Имя пользователя может состоять максимум из 150 символов. Только буквы, цифры и символы @/./+/-/_.', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль',help_text='Пароль должен состоять минимум из 8 символов, содержать как буквы, так и цифры, не быть заведомо простым и не содержать схожую с вашей персональной информацию', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ["title", "post"]
        widgets = {
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Тема поста'
            }),
            "post": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст поста'
            }),
        }

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog, Category, Product
import os
from .forms import BlogForm, UserRegistrationForm, UserLoginForm
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import login, logout
from django.core.mail import send_mail
from cart.forms import CartAddProductForm


def index(request):
    return render(request, 'main/index.html')


def about(request):
    return render(request, 'main/about.html')




def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            email = form.cleaned_data['email']
            # send_mail('Регистрация', 'Поздравляю, вы успешно зарегистрировались на сайте FloriShop', 'gyntera@gmail.com', [email])
            login(request,user)
            messages.success(request, 'Регистрация прошла успешно')
            return redirect('main:index')
        else:
            messages.error(request, 'При регистрации возникла ошибка, пожалуйста попробуйте снова')
    else:
        form = UserRegistrationForm()
    return render(request, 'main/registration.html', {'form': form})


def log_in(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('main:index')
    else:
        form = UserLoginForm()
    return render(request, 'main/login.html', {'form': form})


def log_out(request):
    logout(request)
    return redirect('main:index')

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'main/products/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'main/products/detail.html',
                  {'product': product})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'main/products/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

main/templates/main/products/detail.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="col-lg-4">
    <div class="project">
    <div class="product-detail">
    <div class="image">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" width = "100%">
    </div>
    <div class="info">
        <h1>{{ product.name }}</h1>
    </div>

        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
     <div class="aspiration">
        <p class="price">{{ product.price }}</p>
        {{ product.description|linebreaks }}
     </div>
    </div>


<form  class="form-korzina" action="{% url "cart:cart_add" product.id %}" method="post">
     <div class="inputs">
        {{ cart_product_form }}
        {% csrf_token %}
        <button class = "btn bnt-succsess"  type="submit"> Добавить в корзину</button>
     </div>
</form>
    </div>
    </div>
{% endblock %}

main/templates/main/products/list.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

    <div class="page-title" style="background-image: url({%static 'images/flowers.jpg'%})">
        <div class="container">
            <h1>Товары</h1>
            <div class="polosonka">
                <ul>
                    <li><a href="{% url 'main:index'%}">Главная</a></li>
                    <li><span>Товары</span></li>
                </ul>
            </div>
        </div>
    </div>



    <div class = "widget">
        <h3 class = "widget-title" >Категории</h3>
        <ul class = "widget-list">
            <li {% if not category %} class="selected" {% endif %}>
                <a href="{% url "main:product_list" %}">Все</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>


    <h1>{% if category %}{{ category.name }}{% else %}Все товары{% endif %}</h1>

    {% for product in products %}
        <div class = "product-item">
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" width="100%">
            </a>
            <div class="product-list">
                <div class="info">
                    <h3 href="{{ product.get_absolute_url }}">{{ product.name }}</h3><br>
                </div>
                <span class="price">
                    {{ product.price }}
                </span>
            </div>
        </div>
    {% endfor %}


{% endblock %}