FloriShop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls', namespace='main')),
]

cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'
urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),

    path('list/', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.urls import reverse

class Blog(models.Model):
    title = models.CharField('Тема поста', max_length=99)
    post = models.TextField('Текст поста')


    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'Посты'
        verbose_name_plural = 'Блог'


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_list_by_category',
                       args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey('Category', related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:product_detail',
                       args=[self.id, self.slug])

main/forms.py
from .models import Blog
from django import forms
from django.forms import ModelForm, TextInput, Textarea, EmailField
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', help_text='Имя пользователя может состоять максимум из 150 символов. Только буквы, цифры и символы @/./+/-/_.', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль',help_text='Пароль должен состоять минимум из 8 символов, содержать как буквы, так и цифры, не быть заведомо простым и не содержать схожую с вашей персональной информацию', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ["title", "post"]
        widgets = {
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Тема поста'
            }),
            "post": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст поста'
            }),
        }

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog, Category, Product
import os
from .forms import BlogForm, UserRegistrationForm, UserLoginForm
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import login, logout
from django.core.mail import send_mail
from cart.forms import CartAddProductForm


def index(request):
    return render(request, 'main/index.html')


def about(request):
    return render(request, 'main/about.html')




def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            email = form.cleaned_data['email']
            # send_mail('Регистрация', 'Поздравляю, вы успешно зарегистрировались на сайте FloriShop', 'gyntera@gmail.com', [email])
            login(request,user)
            messages.success(request, 'Регистрация прошла успешно')
            return redirect('main:index')
        else:
            messages.error(request, 'При регистрации возникла ошибка, пожалуйста попробуйте снова')
    else:
        form = UserRegistrationForm()
    return render(request, 'main/registration.html', {'form': form})


def log_in(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('main:index')
    else:
        form = UserLoginForm()
    return render(request, 'main/login.html', {'form': form})


def log_out(request):
    logout(request)
    return redirect('main:index')

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'main/products/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request,
                  'main/products/detail.html',
                  {'product': product})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'main/products/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})

main/templates/main/about.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
О нас
{% endblock %}

{% block content %}

             <div class="page-title" style="background-image: url({%static 'images/flowers.jpg'%})">
                <div class="container">
                    <h1>О нас</h1>
                    <div class="polosonka">
                        <ul>
                            <li><a href="{% url 'main:index'%}">Главная</a></li>
                            <li><span>О нас</span></li>
                        </ul>
                    </div>
                </div>
            </div>

 <div class="container">
                    <div class="row">
                        <div class="col-md-9">

                                <div class="our-team">
                                    <h3 class="bottom-line">Контакты</h3>
                                    <ul type="circle">
                                        <li>Телефон: 8 (999) 999-99-99</li>
                                        <li>Email: florishop@gmail.com</li>
                                        <li>Адрес: ул. Карла Маркса, 59, Хабаровск, Хабаровский край, 680000</li>
                                        <li>Время работы: с 9:00 утра до 22:00</li>
                                    </ul>

                                </div>

                        </div>

                        </div>
                    </div>
                </div>

{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">


    <link rel="stylesheet" href="{% static 'css/grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <title>{% block title %}FloriShop{% endblock %}</title>
</head>



<header>
    <nav>
        <div class="container">

            <a class="logo" href="{% url 'main:index' %}">
                <img src="{%static 'images/logotip.png'%}" alt="FLoriShop">
            </a>
            <button class="burger"><i class="fa fa-bars"></i></button>
            <a>Цветы как украшение жизни </a>

            <ul class="menu top">

                <li class="item"><a href="{% url 'main:product_list' %}">Товары </a></li>
                <li class="item"><a href="{% url 'cart:cart_detail' %}">Корзина</a></li>
                <li class="item"><a href="{% url 'main:about' %}">О нас</a></li>

                {% if request.user.is_authenticated %}Добро пожаловать, {{ user.username }} |<li class="item"><a href="{% url 'main:logout' %}">Выйти</a> </li>
                {% else %}
                    <li class="item"><a  href="{% url 'main:login' %}">Войти</a> </li>
                    <li class="item"><a  href="{% url 'main:registration' %}">Регистрация</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>
</header>


<div id="header">
    <a href="/" class="logo"></a>

    <div id="subheader">
        <div class="container">
            <div class="row">
                <div class="col-xl-3">
                    Ваша корзина пуста
                </div>
            </div>
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <footer>
        <div class="container">
            <a class="logo" href="{% url 'main:index' %}">
                <img src="{%static 'images/logotip.png'%}" alt="Logotip">
            </a>


            <div class="copyright">«FloriShop» ©2020
                <ul type="circle">
                    <li>Телефон: 8 (999) 999-99-99</li>
                    <li>Email: florishop@gmail.com</li>
                </ul>
            </div>
        </div>
    </footer>
</div>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
Главная страница
{% endblock %}

{% block content %}

 <meta name="FloriShop" content="Онлайн-магазин цветов и аксессуаров">

 <div class="main-priv margin">
                    <div class="container">
                        <h3>Интернет-магазин FloriShop приветствует Вас!</h3>
                        <p>Мы предлагаем широкий ассортимент товаров по выгодным для вас ценам и с удобным для вас сервисом. Вы можете легко и быстро заказать букет и порадовать своих близких, друзей, коллег прекрасным подарком к любому празднику.

                            Мы занимаемся продажей и доставкой в Хабаровске:

                            букетов цветов
                            комнатных растений
                            сувениров и подарков
                            мягких игрушек
                            гелиевых шаров</p>
                        <div class="row items">

                            <div class="col-lg-4 col-md-6">
                                <div class="box">
                                    <i class="fa fa-road"></i>
                                    <p class="num">>100</p>
                                    <p>пройденных километров</p>
                                </div>
                            </div>

                            <div class="col-lg-4 col-md-6">
                                <div class="box">
                                    <i class="fa fa-gear"></i>
                                    <p class="num">>1 000 000</p>
                                    <p>Цветов осчастливили людей</p>
                                </div>
                            </div>

                            <div class="col-lg-4 col-md-6">
                                <div class="box">
                                    <i class="fa fa-paw"></i>
                                    <p class="num">>100 000</p>
                                    <p>Плюшевых зверей обрели семью</p>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </main>

{% endblock %}

main/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
Авторизация
{% endblock %}

{% block content %}


    <div class="page-title" style="background-image: url({%static 'images/flowers.jpg'%})">
        <div class="container">
            <h1>Авторизация</h1>
            <div class="polosonka">
                <ul>
                    <li><a href="{% url 'main:index'%}">Главная</a></li>
                    <li><span>Войти</span></li>
                </ul>
            </div>
        </div>
    </div>


    <h1>Авторизация</h1>

       <form class="form-korzina" method="post" >
           <div class="inputs">
               {% csrf_token %}
               {{ form.as_p }}
               <button type="submit" class="btn btn-success">Войти </button>
           </div>
       </form>

{% endblock %}

main/templates/main/registration.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
Регистрация
{% endblock %}

{% block content %}



    <div class="page-title" style="background-image: url({%static 'images/flowers.jpg'%})">
        <div class="container">
            <h1>Регистрация</h1>
            <div class="polosonka">
                <ul>
                    <li><a href="{% url 'main:index'%}">Главная</a></li>
                    <li><span>Регистрация</span></li>
                </ul>
            </div>
        </div>
    </div>



    <div class="container">
        <div class="row">
            <div class="col-xl-9">

                <form class = "form-korzina" action = "{% url 'main:login' %}">
                    <div class="inputs">
                        <button > Вход</button>
                    </div>
                </form>

                <form class="form-korzina" method="post">
                    <div class="inputs">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Зарегистрироваться </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}