FloriShop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls', namespace='main')),
]

cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'
urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('registration/', views.registration, name='registration'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),

    path('list/', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart/detail.html', {'cart': cart})

cart/templates/cart/cart/detail.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
    Ваша корзина
{% endblock %}
{% block content %}

    <div class="page-title" style="background-image: url({%static 'images/flowers.jpg'%})">
        <div class="container">
            <h1>Ваша корзина</h1>
            <div class="polosonka">
                <ul>
                    <li><a href="{% url 'main:index'%}">Главная</a></li>
                    <li><span>Корзина</span></li>
                </ul>
            </div>
        </div>
    </div>


    <table class="korzina">
        <thead>
                <tr>
                <th>Изображение</th>
                <th>Товар</th>
                <th>Количество</th>
                <th>Удалить</th>
                <th>Цена за штуку</th>
                <th>Итоговая цена</th>
            </tr>
        </thead>
        <tbody>




                            {% for item in cart %}
                                {% with product=item.product %}
                                    <tr>
                                        <td>
                                            <a href="{{ product.get_absolute_url }}">
                                                <div class="image">
                                                    <img src="
                                                        {% if product.image %}

                                                        {{ product.image.url }}

                                                        {% else %}
                                                            {% static "img/no_image.png" %}
                                                        {% endif %}" width="100%">
                                                </div>
                                                </a>
                                        </td>
                                        <div class="description">
                                            <td>{{ product.name }}</td>
                                        </div>
                                        <div class="aspiration">
                                            <td>{{ item.quantity }}</td>
                                        </div>

                                        <td><a href="{% url "cart:cart_remove" product.id%}">Удалить</a></td>
                                        <td class="num">{{ item.price }}</td>
                                        <td class="num">{{ item.total_price }}</td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                            <tr class="total">
                                <td>К оплате</td>
                                <td colspan="4"></td>
                                <td class="num">{{ cart.get_total_price }}</td>
                            </tr>


        </tbody>
    </table>

    <form  class="form-korzina">
        <div class="inputs">
            <p class="text-right">
                <a href="{% url "main:product_list" %}" class="button light">Продолжить покупки</a>
                <button class = "btn bnt-succsess" type="submit">Оформить заказ</button>
            </p>
        </div>
    </form>

{% endblock %}